### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Dinver** [aimeos/ai-admin-jsonadm#10]
Hi, bug on almost all pages admin panel:
"hex2bin(): Hexadecimal input string must have an even length"
On clear install same.

Version:
"php": "^7.3|^8.0",
"aimeos/ai-client-html": "2020.10.x-dev",
"aimeos/ai-controller-frontend": "2020.10.x-dev",
"aimeos/aimeos-laravel": "2020.10.x-dev",
"aimeos/map": "~1.8",
"fideloper/proxy": "^4.4",
"fruitcake/laravel-cors": "^2.0",
"guzzlehttp/guzzle": "^7.0.1",
"laravel/framework": "^8.12",
"laravel/tinker": "^2.5",
"laravel/tinker": "^2.0",
"laravel/ui": "^3.0"		

![demo](https://user-images.githubusercontent.com/36528841/101485880-de137380-396c-11eb-82fb-6f89e5775b08.jpg)

**Comment by aimeos** [comment]
This is a bug in symfony/http-foundation and should be closed in v5.2.1. Use v5.1.9 in the meantime.

**Comment by Dinver** [comment]
Thank, this solved the problem.
