### ISSUE TITLE
Decorator Factory

### ISSUE THREAD

**Issue by exemplari** [aimeos/ai-admin-jsonadm#12]
I wanted to add decorator functions to the media controller of the Admin JSON API. As soon as the local decorator is picked up an error is thrown from Aimeos\Admin\JsonAdm\Common\Factory\Base::addClientDecorators line 48 that the interface class is incorrect. 

`
	protected static function addClientDecorators( \Aimeos\Admin\JsonAdm\Iface $client,
		\Aimeos\MShop\Context\Item\Iface $context, string $path ) : \Aimeos\Admin\JsonAdm\Common\Iface
`

It should be Common\Decorator\Iface , not just Common Iface.

`
	protected static function addClientDecorators( \Aimeos\Admin\JsonAdm\Iface $client,
		\Aimeos\MShop\Context\Item\Iface $context, string $path ) : \Aimeos\Admin\JsonAdm\Common\Decorator\Iface
`

This worked for this single decorator but breaks other requests as the original interface is used.

`
protected static function addClientDecorators( \Aimeos\Admin\JsonAdm\Iface $client,
		\Aimeos\MShop\Context\Item\Iface $context, string $path )
`

Ended up just removing the return type. This isnt really a solution but a quick fix, any insight?

**Comment by aimeos** [comment]
\Aimeos\Admin\JsonAdm\Common\Decorator\Iface is the correct return type:
https://github.com/aimeos/ai-admin-jsonadm/blob/master/admin/jsonadm/src/Admin/JsonAdm/Common/Factory/Base.php#L48-L49

This means that your class doesn't inherit from the base class and thus doesn't implement the required interface. Inherit from the decorator base class to fix the problem:
https://github.com/aimeos/ai-admin-jsonadm/blob/master/admin/jsonadm/src/Admin/JsonAdm/Common/Decorator/Base.php

**Comment by exemplari** [comment]
Please recheck my original message and the first link you sent me. I agree
with you \Aimeos\Admin\JsonAdm\Common\Decorator\Iface is the correct return
type:. My class has the correct return type. The add client decorator
function expects the incorrect return type.

https://github.com/aimeos/ai-admin-jsonadm/blob/master/admin/jsonadm/src/Admin/JsonAdm/Common/Factory/Base.php#L48-L49

protected static function addClientDecorators( \Aimeos\Admin\JsonAdm\Iface
$client,
\Aimeos\MShop\Context\Item\Iface $context, string $path ) :
\Aimeos\Admin\JsonAdm\Common\IfaceThe aimeoes code is the problem.

**Comment by exemplari** [comment]
#13

**Comment by aimeos** [comment]
Fixed in https://github.com/aimeos/ai-admin-jsonadm/commit/95089cba99a4f0bd076eabdb3fe285f76f94daa9
