### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by mylgeorge** [aimeos/ai-admin-jsonadm#14]
When 2 or more relationships has the same id not included in jsonadmin response.
  
https://github.com/aimeos/ai-admin-jsonadm/blob/f8cfd0dbc034b75ce5ef4cca442073a8cfd867ec/admin/jsonadm/src/Admin/JsonAdm/Base.php#L207

possible fix:   ```$list[] = $refItem;```

**Comment by aimeos** [comment]
Yes, sounds to be a good solution. Can you please create a pull request with your change?

**Comment by aimeos** [comment]
Merged and will be part of the next release
