### ISSUE TITLE
JsonAdm::createComponent return type error with decorators

### ISSUE THREAD

**Issue by maslii** [aimeos/ai-admin-jsonadm#20]
Method `JsonAdm::createComponent` return type is set to `Aimeos\Admin\JsonAdm\Common\Iface`, but the method itself return `JsonAdm::addComponentDecorators` method which return type is `Aimeos\Admin\JsonAdm\Iface`. After we add decorator we get type error because decorator is an instance of `Aimeos\Admin\JsonAdm\Iface` and not `Aimeos\Admin\JsonAdm\Common\Iface`. Without decorators everything seems ok because `Aimeos\Admin\JsonAdm\Common\Iface` extends from `Aimeos\Admin\JsonAdm\Iface`

Example decorator extends Base decorator class which implements `Aimeos\Admin\JsonAdm\Decorator\Iface` interface which extends from `Aimeos\Admin\JsonAdm\Iface`.

**Comment by maslii** [comment]
[Pull Request](https://github.com/aimeos/ai-admin-jsonadm/pull/21)

**Comment by aimeos** [comment]
The root cause for the problem seems to be here: https://github.com/aimeos/ai-admin-jsonadm/blob/master/src/Admin/JsonAdm/Base.php#L21

Can you add `\Aimeos\Admin\JsonAdm\Iface` and test if it works?
